### ISSUE TITLE
NullPointerException occured : null

### ISSUE THREAD

**Issue by zanedev** [mmurray/play-mustache#12]
Hello we are getting an NPE error on the java side when using #{mustache.print} in a play html groovy template.  The weird thing is it works fine from our development machines (macs) but it is throwing this error on the live server.  We've tried upgrading the jvm and the server and even tried the JDK but it's still happening.  Also we tried changing play from a tomcat deploy to more closely match our local environments but nothing is working.  Please any help would be appreciated as we've written a lot of code in this fashion and we share the templates with our javascript so we'd have to rewrite a lot if we can't use mustache.
## Stack trace:

20:48:52,403 ERROR ~ 

@6al2dd0po
Internal Server Error (500) for request GET /mystuff/people

Execution exception (In {module:mustache-0.2}/app/play/modules/mustache/MustacheTags.java around line 32)
NullPointerException occured : null

play.exceptions.JavaExecutionException
    at play.templates.BaseTemplate.throwException(BaseTemplate.java:90)
    at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:257)
    at play.templates.Template.render(Template.java:26)
    at play.templates.GroovyTemplate.render(GroovyTemplate.java:187)
    at play.mvc.results.RenderTemplate.<init>(RenderTemplate.java:24)
    at play.mvc.Controller.renderTemplate(Controller.java:660)
    at play.mvc.Controller.renderTemplate(Controller.java:640)
    at play.mvc.Controller.render(Controller.java:695)
    at controllers.MyStuff.people(MyStuff.java:183)
    at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:548)
    at play.mvc.ActionInvoker.invoke(ActionInvoker.java:502)
    at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:478)
    at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:473)
    at play.mvc.ActionInvoker.invoke(ActionInvoker.java:161)
    at Invocation.HTTP Request(Play!)
Caused by: java.lang.NullPointerException
    at play.modules.mustache.MustacheTags._template(MustacheTags.java:32)
    at play.modules.mustache.MustacheTags$_template.call(Unknown Source)
    at /app/views/User/people.html.(line:22)
    at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:232)
    ... 13 more

**Comment by zanedev** [comment]
After further debugging it appears that the MustacheSession is null, so somehow the call to MustacheSession session = MustachePlugin.session(); in MustacheTags.java:31 is returning a null session.  I wonder what could cause a null ThreadLocal session on this environment but not our development environment?  Please help.

**Comment by zanedev** [comment]
Definitely a ThreadLocal problem.  Changing MustachePlugin.java to not use threadlocal seems to do the trick.  See the answer provided by CodeTripper for the solution: http://stackoverflow.com/questions/11067073/java-play-mustache-npe-error
