### ISSUE TITLE
NPE in MustacheTags at line 39

### ISSUE THREAD

**Issue by s3u** [mmurray/play-mustache#2]
Hi,

I'm getting an NPE at line 39 

public static void _print(Map<?, ?> args, Closure body, PrintWriter out, ExecutableTemplate template, int fromLine) throws MustacheException, IOException {
36:
         String key = args.get("arg").toString();
37:
         Object context = args.get("context");
38:
         MustacheSession session = MustachePlugin.session();
39:
         out.print(session.toHtml(key, context));
40:
     }

Looking at the source, is this supposed to work like this?

**Comment by s3u** [comment]
Pl ignore my previous note. The stack trace is

play.exceptions.JavaExecutionException
    at play.templates.BaseTemplate.throwException(BaseTemplate.java:88)
    at play.templates.GroovyTemplate.render(GroovyTemplate.java:226)
    at play.mvc.results.RenderTemplate.<init>(RenderTemplate.java:21)
    at play.mvc.Controller.renderTemplate(Controller.java:588)
    at play.mvc.Controller.renderTemplate(Controller.java:568)
    at controllers.Application.index(Application.java:43)
    at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:413)
    at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:408)
    at play.mvc.ActionInvoker.invoke(ActionInvoker.java:182)
    at Invocation.HTTP Request(Play!)
Caused by: java.lang.NullPointerException
    at com.sampullara.mustache.Scope.<init>(Scope.java:43)
    at play.modules.mustache.MustacheSession.toHtml(MustacheSession.java:60)
    at play.modules.mustache.MustacheTags._print(MustacheTags.java:40)
    at play.modules.mustache.MustacheTags$_print.call(Unknown Source)
    at /app/views/mustaches/main.html.(line:23)
    at play.templates.GroovyTemplate.render(GroovyTemplate.java:203)

**Comment by geertbrit** [comment]
Did you manage to resolve this?

**Comment by s3u** [comment]
Sorry - I don't recall.
